---
model: gpt-4o
4o: true
dark-mode: true
pretty: true
stream: false
show-diffs: false
git: false
aiderignore: '.gitignore'
gitignore: true
yes-always: true
auto-commits: false
dirty-commits: false
commit: false
restore-chat-history: false
lint: false
# 'lint-cmd': 'python:ruff check --exit-zero'
# 'test-cmd': 'python:pytest'
vim: true
check-update: false
