---
model: lm_studio/deepseek-r1-distill-qwen-7b
dark-mode: true
edit-format: 'diff'
# pretty: true
# stream: true
# show-diffs: true
git: false
# map-tokens: 2048
# map-multiplier-no-files: 2
aiderignore: '.gitignore'
model-metadata-file: '~/.aider.model.metadata.json'
gitignore: false
yes-always: true
auto-commits: false
dirty-commits: false
commit: false
restore-chat-history: false
lint: false
# 'lint-cmd': 'python:ruff check --exit-zero'
# 'test-cmd': 'python:pytest'
vim: true
check-update: false
# reasoning-effort: 'high'
