wrap = "keep"
number = true
end_of_line = "lf"
validate = true

[plugin.lists]
bullet = "-"
ordered_marker = ")"

exclude = [
    # exclude a single root level file
    "CHANGELOG.md",

    # recursively exclude a root level directory
    ".venv/**",

    # recursively exclude a directory at any level
    "**/node_modules/**",

    # exclude all .txt files
    "**/*.txt",

    # exclude all files that are not suffixed .md
    "**/?", "**/??", "**/???", "**/*[!.]??", "**/*[!m]?", "**/*[!d]",
]
