[global]
quiet        = false
show_hash    = false
upgrade_only = true
target       = "~/.local/bin"

["astral-sh/uv"]
tag           = "0.8.13"
# asset_filters = ["musl"]
# file          = "*"
# target        = "~/.local/bin/"

# ["jqlang/jq"]
# tag           = "jq-1.7.1"
# # asset_filters = []
# # file          = "*"
# # target        = "~/.local/bin/"

["koalaman/shellcheck"]
tag           = "v0.11.0"
# asset_filters = []
# file          = "*"
# target        = "~/.local/bin/"

["JohnnyMorganz/StyLua"]
tag           = "v2.1.0"
# asset_filters = ["musl"]
# file          = "*"
# target        = "~/.local/bin/"

# ["artempyanykh/marksman"]
# tag           = "2024-12-18"
# # asset_filters = [".tar.gz"]
# # file          = "*"
# # target        = "~/.local/bin/"

["Feel-ix-343/markdown-oxide"]
tag           = "v0.25.5"
asset_filters = ['.tar.gz']
# file          = "*"
# target        = "~/.local/bin/"

["quantumsheep/sshs"]
tag           = "4.7.2"
asset_filters = []
# file          = "*"
# target        = "~/.local/bin/"

["direnv/direnv"]
tag           = "v2.37.1"
# asset_filters = []
# file          = "*"
# target        = "~/.local/bin/"

["nektos/act"]
tag           = "v0.2.80"
# asset_filters = []
# file          = "*"
# target        = "~/.local/bin/"

["hadolint/hadolint"]
tag           = "v2.12.0"
# asset_filters = []
# file          = "*"
# target        = "~/.local/bin/"

["marp-team/marp-cli"]
tag           = "v4.2.3"
# asset_filters = []
# file          = "*"
# target        = "~/.local/bin/"

["cli/cli"]
tag           = "v2.76.2"
# asset_filters = [".tar.gz", "^.tar.gz.tar.gz"]
file          = "gh"
# target        = "~/.local/bin/gh"

# ["jetpack-io/devbox"]
# tag           = "0.10.7"
# asset_filters = []
# file          = "*"
# target        = "~/.local/bin/"

# ["ahmetb/kubectx"]
# tag           = "v0.9.5"
# asset_filters = ["kubectx"]
# # file          = "*"
# target        = "~/.local/bin/kubectl-ctx"
#
# ["ahmetb/kubectx"]
# tag           = "v0.9.5"
# asset_filters = ["kubens"]
# # file          = "*"
# target        = "~/.local/bin/kubectl-ns"

# ["keisku/kubectl-explore"]
# tag           = "v0.7.2"
# # asset_filters = []
# # file          = "*"
# target        = "~/.local/bin/kubectl-explore"

# ["corneliusweig/ketall"]
# tag           = "v1.3.8"
# # asset_filters = ["ketall"]
# file          = "ketall*"
# target        = "~/.local/bin/kubectl-get_all"

# ["vladimirvivien/ktop"]
# tag           = "v0.3.7"
# # asset_filters = ["kubectl-ktop"]
# file          = "kubectl-ktop"
# target        = "~/.local/bin/kubectl-ktop"

# ["iximiuz/kexp"]
# tag           = "v0.0.5"
# # asset_filters = []
# # file          = "*"
# target        = "~/.local/bin/kubectl-kexp"

# ["kubescape/kubescape"]
# tag           = "v3.0.3"
# # asset_filters = [".tar.gz"]
# # file          = "*"
# target        = "~/.local/bin/kubectl-kubescape"

# ["derailed/popeye"]
# tag           = "v0.11.2"
# # asset_filters = []
# # file          = "*"
# target        = "~/.local/bin/kubectl-popeye"

# ["tohjustin/kube-lineage"]
# tag           = "v0.5.0"
# # asset_filters = []
# # file          = "*"
# # target        = "~/.local/bin/kubectl-get_lineage"

# ["robscott/kube-capacity"]
# tag           = "v0.7.4"
# # asset_filters = []
# # file          = "*"
# target        = "~/.local/bin/kubectl-capacity"

# ["zegl/kube-score"]
# tag           = "v1.18.0"
# # asset_filters = [".tar.gz"]
# # file          = "*"
# target        = "~/.local/bin/kubectl-score"

# ["boz/kail"]
# tag           = "v0.17.4"
# # asset_filters = ["v3"]
# # file          = "*"
# target        = "~/.local/bin/kubectl-tail"

# ["ahmetb/kubectl-tree"]
# tag           = "v0.4.3"
# # asset_filters = []
# # file          = "*"
# target        = "~/.local/bin/kubectl-tree"

# ["kubepug/kubepug"]
# tag           = "v1.7.1"
# # asset_filters = [".tar.gz", "^.tar.gz."]
# # file          = "*"
# target        = "~/.local/bin/kubectl-deprecations"

# ["https://get.helm.sh/helm-v3.14.4-linux-amd64.tar.gz"]
# # asset_filters = []
# file          = "helm"
# # target        = "~/.local/bin/"

# ["https://releases.hashicorp.com/vault/1.18.4/vault_1.18.4_linux_amd64.zip"]
# # asset_filters = []
# # file          = "*"
# # target        = "~/.local/bin/"

