[general]
import = ["~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.normal]
family = "iMWritingMono Nerd Font"

[window]
# decorations = "None"
decorations_theme_variant = "None"
title = "Terminal"
dynamic_title = true
# dynamic_padding = true
# padding = { x = 0, y = 0 }
# startup_mode = "Fullscreen"
option_as_alt = "both"

# [[keyboard.bindings]]
# action = "SpawnNewInstance"
# key = "a"
# mods = "Alt"
