import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]

[shell]
program = "zsh"
args = ["-lic", 'eval "$(zellij setup --generate-auto-start zsh)"']

# [colors.primary]
# background = "#000000"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "iMWritingMono Nerd Font"

[window]
# decorations = "None"
decorations_theme_variant = "None"
title = "Terminal"
dynamic_title = true
dynamic_padding = true
padding = { x = 10, y = 0 }
# startup_mode = "Fullscreen"
option_as_alt = "both"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "a"
mods = "Alt"
