return {}
-- return {  -- Symbol outline viewer
--   'stevearc/aerial.nvim',
--   dependencies = {
--      "nvim-treesitter/nvim-treesitter",
--      "nvim-tree/nvim-web-devicons"
--   },
--   keys = {
--     { "<leader>co", ":AerialToggle!<CR>", mode = "n", },
--   },
--   opts = {
--     on_attach = function(bufnr)
--       -- Jump forwards/backwards with '{' and '}'
--       vim.keymap.set("n", "{", "<cmd>AerialPrev<CR>", { buffer = bufnr })
--       vim.keymap.set("n", "}", "<cmd>AerialNext<CR>", { buffer = bufnr })
--     end,
--   },
-- }
