return {}
-- return { -- Symbol outline viewer
--   'kevinhwang91/nvim-bqf',
--   ft = 'qf',
--   dependencies = {
--     'nvim-treesitter/nvim-treesitter',
--   },
--   opts = {
--     -- func_map = {
--     --   drop = 'o',
--     --   openc = 'O',
--     --   split = '<C-s>',
--     --   tabdrop = '<C-t>',
--     --   -- set to empty string to disable
--     --   tabc = '',
--     --   ptogglemode = 'z,',
--     -- },
--     -- filter = {
--     --   fzf = {
--     --     action_for = { ['ctrl-s'] = 'split', ['ctrl-t'] = 'tab drop' },
--     --     extra_opts = { '--bind', 'ctrl-o:toggle-all', '--prompt', '> ' },
--     --   },
--     -- },
--   },
-- }
