return {}
-- return {
--   {
--     'nvim-focus/focus.nvim',
--     lazy = false,
--     opts = {
--       enable = true, -- Enable module
--       commands = true, -- Create Focus commands
--       autoresize = {
--           enable = true, -- Enable or disable auto-resizing of splits
--           height_quickfix = 10, -- Set the height of quickfix panel
--       },
--       ui = {
--           number = false, -- Display line numbers in the focussed window only
--           relativenumber = false, -- Display relative line numbers in the focussed window only
--           hybridnumber = false, -- Display hybrid line numbers in the focussed window only
--           absolutenumber_unfocussed = false, -- Preserve absolute numbers in the unfocussed windows
--
--           cursorline = true, -- Display a cursorline in the focussed window only
--           cursorcolumn = false, -- Display cursorcolumn in the focussed window only
--           colorcolumn = {
--               enable = false, -- Display colorcolumn in the foccused window only
--               list = '+1', -- Set the comma-saperated list for the colorcolumn
--           },
--           signcolumn = false, -- Display signcolumn in the focussed window only
--           winhighlight = false, -- Auto highlighting for focussed/unfocussed windows
--       }
--     },
--   },
--   -- {
--   --   "simeji/winresizer",
--   --   cmd = { "WinResizerStartResize", "WinResizerStartMove" },
--   --   keys = { "<leader>=" },
--   --   init = function()
--   --     vim.g.winresizer_start_key = "<leader>="
--   --   end,
--   -- },
-- }
