-- Send code to terminals.
return {}
-- TODO
-- return {
--   'https://github.com/jpalardy/vim-slime',
--   lazy = false,
--   keys = {
--     { '<leader>s', '<Plug>SlimeRegionSend<CR>', mode = 'n', desc = '[S]end text to Zellij pane (motion)' },
--     { '<leader>s', '<Plug>SlimeMotionSend<CR>', mode = 'x', desc = '[S]end text to Zellij pane (visual)' },
--     { '<leader>ss', '<Plug>SlimeLineSend<CR>', mode = 'n', desc = '[S]end line to Zellij pane' },
--   },
--   init = function()
--     vim.g.slime_no_mappings = 1
--     -- vim.g.slime_bracketed_paste = 1
--     -- vim.g.slime_dont_ask_default = 1
--     vim.g.slime_target = 'zellij'
--     vim.g.slime_default_config = {
--       session_id = 'current',
--       relative_pane = 'down',
--     }
--   end,
-- }
