return {}
-- return {
--   {
--     'mg979/vim-visual-multi',
--     lazy = false,
--     config = function()
--       vim.g.VM_default_mappings = 0
--       -- vim.g.VM_maps = {}
--       vim.g.VM_maps = {
--         ['Undo'] = 'u',
--         ['Redo'] = '<C-r>',
--         ['Find Under'] = '<leader>n',
--         ['Find Subword Under'] = '<leader>n',
--         ['Remove Region'] = '<leader>N',
--         ['Seek Prev '] = '<C-Left>',
--         ['Add Cursor Down'] = '<C-Down>',
--         ['Add Cursor Up'] = '<C-Up>',
--         ['Visual All'] = '<leader>*',
--         ['Visual Cursors'] = '<C-Left>',
--         ['Mouse Cursor'] = '<C-LeftMouse>',
--       }
--     end,
--   },
-- }
