[tool.yamlfix]
allow_duplicate_keys = true
comments_min_spaces_from_content = 2
comments_require_starting_space = true
comments_whitelines = 0
explicit_start = true
indent_mapping = 2
indent_offset = 2
indent_sequence = 4
line_length = 88
none_representation = "null"
quote_basic_values = true
quote_representation = "'"
section_whitelines = 1
sequence_style = "flow_style"
whitelines = 1
